# Generated by Django 5.2.7 on 2025-10-21 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('voter_id', models.UUIDField()),
                ('encrypted_vote', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_counted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ballot',
                'verbose_name_plural': 'Ballots',
                'indexes': [models.Index(fields=['voter_id'], name='voting_ball_voter_i_a232f2_idx'), models.Index(fields=['timestamp'], name='voting_ball_timesta_aa8445_idx')],
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voter',
                'verbose_name_plural': 'Voters',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.election')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'unique_together': {('election', 'name')},
            },
        ),
    ]
