# Generated by Django 5.2.7 on 2025-10-22 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20251022_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('labels', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='voting_syst_timesta_112aa2_idx'), models.Index(fields=['metric_name'], name='voting_syst_metric__be6f8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('vote_cast', 'Vote Cast'), ('election_created', 'Election Created'), ('election_started', 'Election Started'), ('election_ended', 'Election Ended'), ('candidate_added', 'Candidate Added'), ('security_check', 'Security Check')], max_length=20)),
                ('details', models.JSONField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hash_value', models.CharField(blank=True, max_length=128)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.election')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='voting_audi_timesta_84c28d_idx'), models.Index(fields=['action'], name='voting_audi_action_f98cc9_idx'), models.Index(fields=['election'], name='voting_audi_electio_50a718_idx')],
            },
        ),
    ]
