# Generated by Django 5.2.7 on 2025-10-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_systemmetrics_auditlog'),
    ]

    operations = [
    ]
