# Generated by Django 5.2.7 on 2025-10-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20251022_1851'),
    ]

    operations = [
    ]
